# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jm81-paginate}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Morgan"]
  s.date = %q{2010-08-11}
  s.description = %q{This paginate library assists in paginating collections and results of database 
queries. It is particularly designed for use with DataMapper and ActiveRecord, 
and for the Merb and Rails frameworks, but can be used in many other situations.
}
  s.email = %q{jmorgan@morgancreative.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "TODO",
     "jm81-paginate.gemspec",
     "lib/helpers/merb.rb",
     "lib/helpers/rails.rb",
     "lib/helpers/shared.rb",
     "lib/jm81-paginate.rb",
     "lib/jm81-paginate/version.rb",
     "lib/paginate/ar.rb",
     "lib/paginate/dm.rb",
     "lib/paginate/simple.rb",
     "lib/paginators/orm.rb",
     "lib/paginators/simple.rb",
     "spec/fixtures/ar.rb",
     "spec/fixtures/dm.rb",
     "spec/helpers/merb_spec.rb",
     "spec/helpers/rails_spec.rb",
     "spec/helpers/shared_spec.rb",
     "spec/paginate/ar_spec.rb",
     "spec/paginate/config_spec.rb",
     "spec/paginate/dm_spec.rb",
     "spec/paginate/simple_spec.rb",
     "spec/paginators/orm_spec.rb",
     "spec/paginators/simple_spec.rb",
     "spec/shared.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jm81/paginate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pagination for DataMapper, ActiveRecord, and Array}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/shared.rb",
     "spec/paginators/orm_spec.rb",
     "spec/paginators/simple_spec.rb",
     "spec/helpers/shared_spec.rb",
     "spec/helpers/merb_spec.rb",
     "spec/helpers/rails_spec.rb",
     "spec/paginate/dm_spec.rb",
     "spec/paginate/config_spec.rb",
     "spec/paginate/simple_spec.rb",
     "spec/paginate/ar_spec.rb",
     "spec/fixtures/dm.rb",
     "spec/fixtures/ar.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

